### ISSUE TITLE
implement HA config flow

### ISSUE THREAD

**Issue by zigul** [zigul/HomeAssistant-CEZdistribuce#12]

**Comment by jirimitura** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 14:14:51 (1 occurrences)
Last logged: 14:14:51

Entity binary_sensor.nizky_tarif (<class 'custom_components.cezdistribuce.binary_sensor.CezDistribuce'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by jirimitura** [comment]
co s tím ?

**Comment by jirimitura** [comment]
co mám dodat? , kde hledat ?

**Comment by pokornyIt** [comment]
Hi, problem solved in version 0.4.5
