### ISSUE TITLE
Update for binary sensor fails

### ISSUE THREAD

**Issue by Antoninsm** [zigul/HomeAssistant-CEZdistribuce#19]
Update for sensor often fails with error 'Connection aborted.', RemoteDisconnected('Remote end closed connection without response') - see attached file with full error. Seams like cez will not answer to request made by home assistant. What can I do about this error.
[CEZ distribuce.txt](https://github.com/zigul/HomeAssistant-CEZdistribuce/files/11284070/CEZ.distribuce.txt)

**Comment by pokornyIt** [comment]
In the HACS re-download CEZ Distribuce CZ and restart Home Assistant.
