### ISSUE TITLE
Problémy s entitou

### ISSUE THREAD

**Issue by Beny44** [zigul/HomeAssistant-CEZdistribuce#22]
Mám problémy s nedostupností entity. Mám psolední HA a poslední integraci.
Je to jen o nové verzi?
Díky za info

![obrazek](https://github.com/zigul/HomeAssistant-CEZdistribuce/assets/80783387/a29b488b-a299-4cfe-9f10-6c0017ea2a02)

**Comment by honza-kasik** [comment]
Hello, I went to integration page in HACS in my HASS instance, clicked three dots at right top corner and clicked re-download and restarted the instance. Everything works again.

**Comment by pokornyIt** [comment]
Solved by @honza-kasik
