### ISSUE TITLE
Chyba: Tato entita není integrací cezdistribuce poskytována.

### ISSUE THREAD

**Issue by Festus141** [zigul/HomeAssistant-CEZdistribuce#33]
### Zkontrolujte existující problémy

- [X] Completed

### Verze

0.4.9

### Napište svůj dotaz nebo s čím potřebujete pomoci

Nastaveno ručně - region i code (malé i velké písmena) a píše chybu integrace :( prosím o pomoc

<img width="609" alt="Snímek obrazovky 2024-04-20 v 12 05 22" src="https://github.com/zigul/HomeAssistant-CEZdistribuce/assets/78319042/812b5032-3c5d-4286-8681-4b2323af2c37">
<img width="524" alt="Snímek obrazovky 2024-04-20 v 12 03 53" src="https://github.com/zigul/HomeAssistant-CEZdistribuce/assets/78319042/68dbc432-68f3-4133-ad63-8133d143ed51">
<img width="593" alt="Snímek obrazovky 2024-04-20 v 12 03 42" src="https://github.com/zigul/HomeAssistant-CEZdistribuce/assets/78319042/646bdbd8-f3d7-470a-a3ff-26b0d020d016">

**Comment by pokornyIt** [comment]
Hi, bohužel systém na straně ČEZ Distribuce žádá zadání kód bez nul tj. A1B7DP1 místo A1B7DP01.
Vše se dá otestovat na [oficiální sztránce](https://www.cezdistribuce.cz/cs/pro-zakazniky/potrebuji-vyresit/stavajici-pripojeni/casy-spinani-nizkeho-tarifu?area=stred&code=A1B7DP1#HdoCalculator)
