### ISSUE TITLE
Problem s integraci

### ISSUE THREAD

**Issue by jane1e** [zigul/HomeAssistant-CEZdistribuce#34]
### Zkontrolujte existující problémy

- [X] Completed

### Verze

0.4.9

### Napište svůj dotaz nebo s čím potřebujete pomoci

Dobry den vsem, 
po rucnim nainstalovani do nejnovejsi ver. HASS me binarni sensor nefunguje. 

binary_sensor:
 - platform: cezdistribuce
   name: stred_aku8v5
   region: vychod
   code: AKU8V5

hass hlasi: This entity is no longer being provided by the cezdistribuce integration. If the entity is no longer in use, delete it in settings.

asi nejsem sam: https://www.homeassistant-cz.cz/viewtopic.php?t=1237

diky
JJ

**Comment by pokornyIt** [comment]
Ahoj, musím si spinout čistý HA a zkusit, ale zatím se mi toto nikdy nestalo. Můžeš prosím přiložit soubor, ve kterém je definice toho sensoru (prosím očištěný o privátní informace)?

**Comment by pokornyIt** [comment]
Ok, problém je v definici lokálních hodnot.

**Comment by pokornyIt** [comment]
Solve in version 0.5.0
