### ISSUE TITLE
Doplnenie Price Vt/Nt

### ISSUE THREAD

**Issue by matomatusov** [zigul/HomeAssistant-CEZdistribuce#36]
### Zkontrolujte existující požadavky

- [X] Completed

### Popište řešení, které chcete

Nešlo by doplniť do konfigurace cenu vysokého a nízkeho tarifu?  Napr. do binary_sensor. 
Niečo ako 
    price_vt: "1.53385"
    price_nt: "1.37943"

**Comment by pokornyIt** [comment]
Osobně nevidím důvod. Uvedená záležitost je snadno řešitelná pomocí helperů a template které jsou standardně v HA.
