### ISSUE TITLE
CEZ distribuce integration

### ISSUE THREAD

**Issue by Pavel5710** [zigul/HomeAssistant-CEZdistribuce#37]
### Zkontrolujte existující problémy

- [X] Completed

### Verze

0.5.0

### Napište svůj dotaz nebo s čím potřebujete pomoci

Hello, I have just started with Home Assistant and one of my first projects from HACS is CEZ distribuce integration.
I have downloaded the files into custom_ components:
![image](https://github.com/zigul/HomeAssistant-CEZdistribuce/assets/170193624/6835c8a7-a7af-493b-b8b4-e5749e6967f4)
And added the binary_sensor into configuration.yaml:
![image](https://github.com/zigul/HomeAssistant-CEZdistribuce/assets/170193624/57b6d50c-6f05-4ada-ad43-40d7fc3887e2)
What are next steps in order to see the application in a dashboard?
Thank you very much indeed.
Best regards
Pavel

**Comment by pokornyIt** [comment]
Hi, it's simple. Restart HA. Look into Devices & services => Entities and search stred_a1b5dp6 or cezdistribuce. When you see a binary sensor you can use it in automation and other stuff.
Another approach is to use Developer tools => states and write stred_ into Entity filter.

**Comment by Pavel5710** [comment]
Thanks a lot
